// Product 0.1 review prototypes. These do not invoke product data or a provider.
export type DesignState = { id: string; name: string; text: string; action: string; next: string };
export type DesignFlow = { id: string; title: string; summary: string; states: readonly DesignState[] };
export const DESIGN_FLOWS: readonly DesignFlow[] = [
  { id: "UI-03", title: "对话", summary: "保留用户原文，清楚说明完成、拒绝、取消、断线与重试。",
    states: [
      { id: "empty", name: "空会话", text: "还没有对话。模型未连接时可以查看本地资料。", action: "准备发送", next: "running" },
      { id: "running", name: "运行中", text: "仅一个活动运行；页面切换保留该运行。输出尚未代表任务已保存。", action: "查看正常完成", next: "completed" },
      { id: "completed", name: "正常完成", text: "建议已展示；只有用户另行确认且Core提交成功，任务才算保存。", action: "返回空会话", next: "empty" },
      { id: "refused", name: "模型拒绝", text: "本次请求未执行，说明拒绝原因并保留原文；可修改请求，不自动重试。", action: "修改原文", next: "empty" },
      { id: "cancelling", name: "取消中", text: "等待服务端终态；旧运行的后续事件不能污染新运行。", action: "查看已取消", next: "cancelled" },
      { id: "cancelled", name: "已取消", text: "保留输入；取消不撤销此前已提交的数据变更。", action: "返回空会话", next: "empty" },
      { id: "offline", name: "模型离线", text: "模型连接已中断；本地资料仍可用，原输入保留。", action: "显式重试", next: "running" },
      { id: "error", name: "运行错误", text: "展示故障来源与可操作说明，保留输入；不无限重试消耗额度。", action: "显式重试", next: "running" },
      { id: "recovered", name: "重启回读（设计）", text: "历史应从Core恢复；旧运行标为interrupted，不自动重放；保留尚未发送的输入。", action: "返回空会话", next: "empty" },
    ] },
  { id: "UI-04", title: "任务确认", summary: "模型建议与真正保存分开；拒绝或参数变化需要清楚反馈。",
    states: [
      { id: "pending", name: "待确认", text: "准备创建：整理出差安排。确认前尚未写入。", action: "查看参数修改", next: "editing" },
      { id: "empty", name: "空列表", text: "尚无任务建议，也没有待确认请求；不会显示虚构的待保存卡片。", action: "查看合成建议", next: "pending" },
      { id: "editing", name: "参数修改", text: "日期或标题改变后重新确认新的内容；旧卡片授权失效。", action: "重新确认", next: "executing" },
      { id: "executing", name: "执行中", text: "同一确认请求重复点击不得创建多条任务。等待Core提交回执。", action: "查看成功", next: "completed" },
      { id: "completed", name: "成功（设计状态）", text: "真正产品以Core回执驱动此状态；本设计稿没有保存任务。", action: "返回待确认", next: "pending" },
      { id: "refused", name: "已拒绝", text: "本次建议未保存，不自动重复请求授权。", action: "查看新建议", next: "pending" },
      { id: "error", name: "失败 / 修改冲突", text: "失败保留卡片；任务已被修改时先刷新，再确认新的参数。", action: "刷新后重新确认", next: "editing" },
      { id: "offline", name: "本地服务离线", text: "尚不能确认是否已提交；恢复连接后查询原请求回执，避免重复任务。", action: "查看恢复回读", next: "recovered" },
      { id: "cancelled", name: "已取消", text: "待执行前取消不写入；已提交的变更不会因取消而撤销。", action: "返回待确认", next: "pending" },
      { id: "recovered", name: "恢复回读", text: "先查询原请求回执，再决定是否重试；不能因重启重新创建同一任务。", action: "查看回执成功示例", next: "completed" },
    ] },
  { id: "UI-06", title: "记忆", summary: "保存记忆与允许外发是独立决定；来源与遗忘责任可查看。",
    states: [
      { id: "candidate", name: "候选", text: "建议记住：你偏好中文回复。来源：用户消息。候选尚未保存，也不发送给模型。", action: "查看仅本地确认", next: "local" },
      { id: "empty", name: "空列表", text: "没有已确认记忆。没有候选时不展示虚构条目。", action: "查看合成候选", next: "candidate" },
      { id: "local", name: "已确认 · 仅本地", text: "保存和外发分别控制；未批准的新Provider不能取得本条记忆。", action: "查看外发授权", next: "outbound" },
      { id: "outbound", name: "允许指定Provider外发", text: "本轮上下文应展示具体来源与范围；预算不足必须明确摘要或截断。", action: "查看修改 / 遗忘", next: "forgotten" },
      { id: "forgotten", name: "修改 / 遗忘", text: "未来停止使用并清理派生缓存；已有原始消息、云端内容和旧备份范围另行说明。", action: "查看空列表", next: "empty" },
      { id: "refused", name: "已拒绝", text: "候选没有保存，也没有取得外发授权。", action: "返回候选", next: "candidate" },
      { id: "error", name: "授权失效 / 修改冲突", text: "失败关闭，不能悄悄发送旧内容；刷新后重新确认。", action: "返回候选", next: "candidate" },
      { id: "offline", name: "模型离线", text: "仍可管理本地条目；不能把模型离线当成外发已完成。", action: "查看仅本地状态", next: "local" },
      { id: "cancelled", name: "已取消", text: "取消确认不保存，也不改变既有授权。", action: "返回候选", next: "candidate" },
      { id: "recovered", name: "重启回读（设计）", text: "从Core恢复已确认条目和指定Provider授权；未完成确认不自动重放。", action: "查看仅本地示例", next: "local" },
    ] },
  { id: "UI-08", title: "恢复", summary: "先检查，再在新目录恢复，最后由用户决定切换。",
    states: [
      { id: "empty", name: "没有恢复包", text: "备份包含版本化业务数据与加密身份材料，不含Provider登录和待执行授权。", action: "查看合成包预检", next: "preflight" },
      { id: "preflight", name: "预检", text: "展示备份时间、Navigator、Schema和数据数量，检查资源上限及完整性。", action: "查看隔离校验", next: "validating" },
      { id: "validating", name: "隔离恢复校验", text: "新目录核验身份、引用、迁移和数量。原库仍可使用，尚未切换。", action: "查看可切换", next: "ready" },
      { id: "ready", name: "可切换（设计状态）", text: "资料已校验；官方模型需重新认证。仅显式确认才切换使用恢复资料。", action: "保留原库，返回入口", next: "empty" },
      { id: "completed", name: "恢复完成（设计状态）", text: "合成示例已切换到恢复资料；原库保留。官方模型仍需重新认证。", action: "返回入口", next: "empty" },
      { id: "refused", name: "拒绝切换", text: "继续使用原库；已校验的恢复资料不自动替换当前资料。", action: "返回入口", next: "empty" },
      { id: "error", name: "错误口令 / 损坏 / 过新版本", text: "保留原库与失败证据；不把换旧App当成必然可回滚数据。", action: "重新预检", next: "preflight" },
      { id: "cancelled", name: "已取消", text: "取消预检或隔离恢复不修改原库。", action: "返回入口", next: "empty" },
      { id: "offline", name: "模型离线", text: "模型离线不阻碍资料恢复；切换前仍必须完成本地预检与隔离校验。", action: "开始预检", next: "preflight" },
      { id: "recovered", name: "重启后恢复入口", text: "继续使用原库，未确认的切换不自动执行；重新核验隔离目录后再确认。", action: "重新预检", next: "preflight" },
    ] },
];
